const { app, BrowserWindow, ipcMain, nativeTheme } = require('electron');
const path = require('path');
const fs = require('fs');
const { fork } = require('child_process');

let mainWindow = null;
let botProcess = null;
let botLogs = [];
const MAX_LOGS = 500;

// ── Config paths ──
function getConfigDir() {
  const dir = path.join(app.getPath('userData'), 'config');
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  return dir;
}

function getConfigPath() {
  return path.join(getConfigDir(), 'settings.json');
}

function loadConfig() {
  try {
    const raw = fs.readFileSync(getConfigPath(), 'utf-8');
    return JSON.parse(raw);
  } catch {
    return {};
  }
}

function saveConfig(config) {
  fs.writeFileSync(getConfigPath(), JSON.stringify(config, null, 2));
}

// ── Write .env from config ──
function writeEnvFile(config) {
  const botDir = app.isPackaged
    ? path.join(process.resourcesPath, 'bot')
    : path.join(__dirname, '..');

  const lines = [
    `# Auto-generated by Wildtrade Desktop`,
    `SOLANA_RPC_HELIUS=${config.SOLANA_RPC_HELIUS || 'https://mainnet.helius-rpc.com/?api-key=YOUR_KEY'}`,
    `SOLANA_RPC_QUICKNODE=${config.SOLANA_RPC_QUICKNODE || ''}`,
    `SOLANA_RPC_PUBLIC=https://api.mainnet-beta.solana.com`,
    `HELIUS_API_KEY=${config.HELIUS_API_KEY || ''}`,
    `HELIUS_WEBHOOK_URL=${config.HELIUS_WEBHOOK_URL || ''}`,
    `HELIUS_WEBHOOK_SECRET=${config.HELIUS_WEBHOOK_SECRET || ''}`,
    `WALLET_PRIVATE_KEY=${config.WALLET_PRIVATE_KEY || ''}`,
    `WALLET_PUBLIC_KEY=${config.WALLET_PUBLIC_KEY || '11111111111111111111111111111111'}`,
    `PAPER_TRADING=${config.PAPER_TRADING !== false ? 'true' : 'false'}`,
    `AUTONOMOUS_MODE=${config.AUTONOMOUS_MODE === true ? 'true' : 'false'}`,
    `MAX_POSITION_SIZE_SOL=${config.MAX_POSITION_SIZE_SOL || '1.0'}`,
    `TOTAL_BUDGET_SOL=${config.TOTAL_BUDGET_SOL || '1.0'}`,
    `MIN_SCORE_THRESHOLD=${config.MIN_SCORE_THRESHOLD || '65'}`,
    `DCA_DELAY_LEG1_MS=${config.DCA_DELAY_LEG1_MS || '120000'}`,
    `DCA_DELAY_LEG2_MS=${config.DCA_DELAY_LEG2_MS || '300000'}`,
    `JUPITER_API_BASE=https://quote-api.jup.ag/v6`,
    `JUPITER_SLIPPAGE_BPS=${config.JUPITER_SLIPPAGE_BPS || '300'}`,
    `RUGCHECK_API_BASE=https://api.rugcheck.xyz/v1`,
    `RUGCHECK_MIN_SCORE=${config.RUGCHECK_MIN_SCORE || '70'}`,
    `PUMPPORTAL_WS_URL=wss://pumpportal.fun/api/data`,
    `TWITTER_BEARER_TOKEN=${config.TWITTER_BEARER_TOKEN || ''}`,
    `TWITTER_KOL_USER_IDS=${config.TWITTER_KOL_USER_IDS || ''}`,
    `TWITTER_POLL_INTERVAL_MS=${config.TWITTER_POLL_INTERVAL_MS || '60000'}`,
    `SMART_MONEY_WALLETS=${config.SMART_MONEY_WALLETS || ''}`,
    `OPENROUTER_API_KEY=${config.OPENROUTER_API_KEY || ''}`,
    `OPENROUTER_BASE_URL=https://openrouter.ai/api/v1`,
    `FINDER_MODEL=${config.FINDER_MODEL || 'anthropic/claude-sonnet-4-5'}`,
    `TRADER_MODEL=${config.TRADER_MODEL || 'openai/gpt-4o-mini'}`,
    `AUDITOR_MODEL=${config.AUDITOR_MODEL || 'openai/gpt-4o-mini'}`,
    `SOCKET_IO_PORT=3001`,
    `SOCKET_IO_CORS_ORIGIN=http://localhost:3000`,
    `PGLITE_DATA_DIR=${path.join(getConfigDir(), 'db')}`,
    `LOG_LEVEL=info`,
  ];

  const envPath = path.join(botDir, '.env');
  fs.writeFileSync(envPath, lines.join('\n'));
  return envPath;
}

// ── Bot lifecycle ──
function startBot() {
  if (botProcess) return;

  const config = loadConfig();
  writeEnvFile(config);

  const botScript = app.isPackaged
    ? path.join(process.resourcesPath, 'bot', 'dist', 'bot.cjs')
    : path.join(__dirname, '..', 'dist', 'bot.cjs');

  if (!fs.existsSync(botScript)) {
    sendToRenderer('bot:error', 'Bot not built. Run "npm run build:bot" first.');
    return;
  }

  botLogs = [];
  sendToRenderer('bot:status', 'starting');

  botProcess = fork(botScript, [], {
    cwd: app.isPackaged ? path.join(process.resourcesPath, 'bot') : path.join(__dirname, '..'),
    env: { ...process.env, ...dotenvParse(config) },
    stdio: ['pipe', 'pipe', 'pipe', 'ipc'],
  });

  botProcess.stdout.on('data', (data) => {
    const line = data.toString().trim();
    if (line) addLog('info', line);
  });

  botProcess.stderr.on('data', (data) => {
    const line = data.toString().trim();
    if (line) addLog('error', line);
  });

  botProcess.on('message', (msg) => {
    sendToRenderer('bot:message', msg);
  });

  botProcess.on('exit', (code) => {
    addLog('info', `Bot process exited with code ${code}`);
    botProcess = null;
    sendToRenderer('bot:status', 'stopped');
  });

  botProcess.on('error', (err) => {
    addLog('error', `Bot error: ${err.message}`);
    botProcess = null;
    sendToRenderer('bot:status', 'error');
  });

  sendToRenderer('bot:status', 'running');
}

function stopBot() {
  if (!botProcess) return;
  botProcess.kill('SIGTERM');
  setTimeout(() => {
    if (botProcess) {
      botProcess.kill('SIGKILL');
      botProcess = null;
    }
  }, 5000);
  sendToRenderer('bot:status', 'stopping');
}

function dotenvParse(config) {
  const env = {};
  for (const [key, value] of Object.entries(config)) {
    if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') {
      env[key] = String(value);
    }
  }
  return env;
}

function addLog(level, message) {
  const entry = { time: Date.now(), level, message };
  botLogs.push(entry);
  if (botLogs.length > MAX_LOGS) botLogs.shift();
  sendToRenderer('bot:log', entry);
}

function sendToRenderer(channel, data) {
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send(channel, data);
  }
}

// ── Window ──
function createWindow() {
  nativeTheme.themeSource = 'dark';

  mainWindow = new BrowserWindow({
    width: 1100,
    height: 750,
    minWidth: 800,
    minHeight: 600,
    titleBarStyle: 'hiddenInset',
    backgroundColor: '#0d1117',
    webPreferences: {
      preload: path.join(__dirname, 'preload.cjs'),
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  mainWindow.loadFile(path.join(__dirname, '..', 'ui', 'index.html'));

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
}

// ── IPC Handlers ──
ipcMain.handle('config:load', () => loadConfig());
ipcMain.handle('config:save', (_, config) => {
  saveConfig(config);
  return { ok: true };
});

ipcMain.handle('bot:start', () => {
  startBot();
  return { ok: true };
});

ipcMain.handle('bot:stop', () => {
  stopBot();
  return { ok: true };
});

ipcMain.handle('bot:status', () => {
  return botProcess ? 'running' : 'stopped';
});

ipcMain.handle('bot:logs', () => botLogs);

// ── App lifecycle ──
app.whenReady().then(createWindow);

app.on('window-all-closed', () => {
  stopBot();
  app.quit();
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) createWindow();
});

app.on('before-quit', () => {
  stopBot();
});
