const { app, BrowserWindow, ipcMain, nativeTheme } = require('electron');
const path = require('path');
const fs = require('fs');
const { fork } = require('child_process');

let mainWindow = null;
let botProcess = null;
let botLogs = [];
const MAX_LOGS = 500;

// ── Config paths ──
function getConfigDir() {
  const dir = path.join(app.getPath('userData'), 'config');
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  return dir;
}

function getConfigPath() {
  return path.join(getConfigDir(), 'settings.json');
}

function loadConfig() {
  try {
    const raw = fs.readFileSync(getConfigPath(), 'utf-8');
    return JSON.parse(raw);
  } catch {
    return {};
  }
}

function saveConfig(config) {
  fs.writeFileSync(getConfigPath(), JSON.stringify(config, null, 2));
}

// ── Write .env from config ──
function writeEnvFile(config) {
  const botDir = app.isPackaged
    ? path.join(process.resourcesPath, 'bot')
    : path.join(__dirname, '..');

  const lines = [
    `# Auto-generated by Wildtrade Desktop`,
    `SOLANA_RPC_HELIUS=${config.SOLANA_RPC_HELIUS || 'https://mainnet.helius-rpc.com/?api-key=YOUR_KEY'}`,
    `SOLANA_RPC_QUICKNODE=${config.SOLANA_RPC_QUICKNODE || ''}`,
    `SOLANA_RPC_PUBLIC=https://api.mainnet-beta.solana.com`,
    `HELIUS_API_KEY=${config.HELIUS_API_KEY || ''}`,
    `HELIUS_WEBHOOK_URL=${config.HELIUS_WEBHOOK_URL || ''}`,
    `HELIUS_WEBHOOK_SECRET=${config.HELIUS_WEBHOOK_SECRET || ''}`,
    `WALLET_PRIVATE_KEY=${config.WALLET_PRIVATE_KEY || ''}`,
    `WALLET_PUBLIC_KEY=${config.WALLET_PUBLIC_KEY || '11111111111111111111111111111111'}`,
    `PAPER_TRADING=${config.PAPER_TRADING !== false ? 'true' : 'false'}`,
    `AUTONOMOUS_MODE=${config.AUTONOMOUS_MODE === true ? 'true' : 'false'}`,
    `MAX_POSITION_SIZE_SOL=${config.MAX_POSITION_SIZE_SOL || '1.0'}`,
    `TOTAL_BUDGET_SOL=${config.TOTAL_BUDGET_SOL || '1.0'}`,
    `MIN_SCORE_THRESHOLD=${config.MIN_SCORE_THRESHOLD || '65'}`,
    `DCA_DELAY_LEG1_MS=${config.DCA_DELAY_LEG1_MS || '120000'}`,
    `DCA_DELAY_LEG2_MS=${config.DCA_DELAY_LEG2_MS || '300000'}`,
    `JUPITER_API_BASE=https://quote-api.jup.ag/v6`,
    `JUPITER_SLIPPAGE_BPS=${config.JUPITER_SLIPPAGE_BPS || '300'}`,
    `RUGCHECK_API_BASE=https://api.rugcheck.xyz/v1`,
    `RUGCHECK_MIN_SCORE=${config.RUGCHECK_MIN_SCORE || '70'}`,
    `PUMPPORTAL_WS_URL=wss://pumpportal.fun/api/data`,
    `TWITTER_BEARER_TOKEN=${config.TWITTER_BEARER_TOKEN || ''}`,
    `TWITTER_KOL_USER_IDS=${config.TWITTER_KOL_USER_IDS || ''}`,
    `TWITTER_POLL_INTERVAL_MS=${config.TWITTER_POLL_INTERVAL_MS || '60000'}`,
    `SMART_MONEY_WALLETS=${config.SMART_MONEY_WALLETS || ''}`,
    `OPENROUTER_API_KEY=${config.OPENROUTER_API_KEY || ''}`,
    `OPENROUTER_BASE_URL=https://openrouter.ai/api/v1`,
    `FINDER_MODEL=${config.FINDER_MODEL || 'anthropic/claude-sonnet-4-5'}`,
    `TRADER_MODEL=${config.TRADER_MODEL || 'openai/gpt-4o-mini'}`,
    `AUDITOR_MODEL=${config.AUDITOR_MODEL || 'openai/gpt-4o-mini'}`,
    `SOCKET_IO_PORT=3001`,
    `SOCKET_IO_CORS_ORIGIN=http://localhost:3000`,
    `PGLITE_DATA_DIR=${path.join(getConfigDir(), 'db')}`,
    `LOG_LEVEL=info`,
  ];

  const envPath = path.join(botDir, '.env');
  fs.writeFileSync(envPath, lines.join('\n'));
  return envPath;
}

// ── Bot lifecycle ──
function startBot() {
  if (botProcess) return;

  const config = loadConfig();
  writeEnvFile(config);

  const botScript = app.isPackaged
    ? path.join(process.resourcesPath, 'bot', 'dist', 'bot.cjs')
    : path.join(__dirname, '..', 'dist', 'bot.cjs');

  if (!fs.existsSync(botScript)) {
    sendToRenderer('bot:error', 'Bot not built. Run "npm run build:bot" first.');
    return;
  }

  botLogs = [];
  sendToRenderer('bot:status', 'starting');

  botProcess = fork(botScript, [], {
    cwd: app.isPackaged ? path.join(process.resourcesPath, 'bot') : path.join(__dirname, '..'),
    env: { ...process.env, ...buildBotEnv(config) },
    stdio: ['pipe', 'pipe', 'pipe', 'ipc'],
  });

  botProcess.stdout.on('data', (data) => {
    const line = data.toString().trim();
    if (line) addLog('info', line);
  });

  botProcess.stderr.on('data', (data) => {
    const line = data.toString().trim();
    if (line) addLog('error', line);
  });

  botProcess.on('message', (msg) => {
    sendToRenderer('bot:message', msg);
  });

  botProcess.on('exit', (code) => {
    addLog('info', `Bot process exited with code ${code}`);
    botProcess = null;
    sendToRenderer('bot:status', 'stopped');
  });

  botProcess.on('error', (err) => {
    addLog('error', `Bot error: ${err.message}`);
    botProcess = null;
    sendToRenderer('bot:status', 'error');
  });

  sendToRenderer('bot:status', 'running');
}

function stopBot() {
  if (!botProcess) return;
  botProcess.kill('SIGTERM');
  setTimeout(() => {
    if (botProcess) {
      botProcess.kill('SIGKILL');
      botProcess = null;
    }
  }, 5000);
  sendToRenderer('bot:status', 'stopping');
}

function dotenvParse(config) {
  const env = {};
  for (const [key, value] of Object.entries(config)) {
    if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') {
      env[key] = String(value);
    }
  }
  return env;
}

// Build complete env for the bot process with all defaults
function buildBotEnv(config) {
  const parsed = dotenvParse(config);
  return {
    OPENROUTER_API_KEY: parsed.OPENROUTER_API_KEY || '',
    OPENROUTER_BASE_URL: 'https://openrouter.ai/api/v1',
    WALLET_PUBLIC_KEY: parsed.WALLET_PUBLIC_KEY || '11111111111111111111111111111111',
    WALLET_PRIVATE_KEY: parsed.WALLET_PRIVATE_KEY || '',
    SOLANA_RPC_HELIUS: parsed.SOLANA_RPC_HELIUS || 'https://api.mainnet-beta.solana.com',
    SOLANA_RPC_PUBLIC: 'https://api.mainnet-beta.solana.com',
    HELIUS_API_KEY: parsed.HELIUS_API_KEY || '',
    PAPER_TRADING: parsed.PAPER_TRADING === 'false' ? 'false' : 'true',
    AUTONOMOUS_MODE: parsed.AUTONOMOUS_MODE === 'true' ? 'true' : 'false',
    MAX_POSITION_SIZE_SOL: parsed.MAX_POSITION_SIZE_SOL || '1.0',
    TOTAL_BUDGET_SOL: parsed.TOTAL_BUDGET_SOL || '1.0',
    MIN_SCORE_THRESHOLD: parsed.MIN_SCORE_THRESHOLD || '65',
    JUPITER_API_BASE: 'https://quote-api.jup.ag/v6',
    JUPITER_SLIPPAGE_BPS: parsed.JUPITER_SLIPPAGE_BPS || '300',
    RUGCHECK_API_BASE: 'https://api.rugcheck.xyz/v1',
    RUGCHECK_MIN_SCORE: parsed.RUGCHECK_MIN_SCORE || '70',
    PUMPPORTAL_WS_URL: 'wss://pumpportal.fun/api/data',
    TWITTER_BEARER_TOKEN: parsed.TWITTER_BEARER_TOKEN || '',
    TWITTER_KOL_USER_IDS: parsed.TWITTER_KOL_USER_IDS || '',
    SMART_MONEY_WALLETS: parsed.SMART_MONEY_WALLETS || '',
    FINDER_MODEL: parsed.FINDER_MODEL || 'anthropic/claude-sonnet-4-5',
    TRADER_MODEL: parsed.TRADER_MODEL || 'openai/gpt-4o-mini',
    AUDITOR_MODEL: parsed.AUDITOR_MODEL || 'openai/gpt-4o-mini',
    SOCKET_IO_PORT: '3001',
    SOCKET_IO_CORS_ORIGIN: 'http://localhost:3000',
    PGLITE_DATA_DIR: path.join(getConfigDir(), 'db'),
    LOG_LEVEL: 'info',
  };
}

function addLog(level, message) {
  const entry = { time: Date.now(), level, message };
  botLogs.push(entry);
  if (botLogs.length > MAX_LOGS) botLogs.shift();
  sendToRenderer('bot:log', entry);

  // Parse for trade activity to feed into chat context
  parseLogForActivity(message);
}

function sendToRenderer(channel, data) {
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send(channel, data);
  }
}

// ── Window ──
function createWindow() {
  nativeTheme.themeSource = 'dark';

  mainWindow = new BrowserWindow({
    width: 1100,
    height: 750,
    minWidth: 800,
    minHeight: 600,
    titleBarStyle: 'hiddenInset',
    backgroundColor: '#0d1117',
    webPreferences: {
      preload: path.join(__dirname, 'preload.cjs'),
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  mainWindow.loadFile(path.join(__dirname, '..', 'ui', 'index.html'));

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
}

// ── IPC Handlers ──
ipcMain.handle('config:load', () => loadConfig());
ipcMain.handle('config:save', (_, config) => {
  saveConfig(config);
  return { ok: true };
});

ipcMain.handle('bot:start', () => {
  startBot();
  return { ok: true };
});

ipcMain.handle('bot:stop', () => {
  stopBot();
  return { ok: true };
});

ipcMain.handle('bot:status', () => {
  return botProcess ? 'running' : 'stopped';
});

ipcMain.handle('bot:logs', () => botLogs);

// ── AI Chat via OpenRouter ──
let chatHistory = [];

// Trade activity log for the chat to reference
let tradeActivity = [];
const MAX_TRADE_ACTIVITY = 50;

function addTradeActivity(entry) {
  tradeActivity.push({ ...entry, timestamp: Date.now() });
  if (tradeActivity.length > MAX_TRADE_ACTIVITY) tradeActivity.shift();
  // Also push to renderer as a chat notification
  sendToRenderer('bot:trade-update', entry);
}

// Parse bot logs for trade activity and smart money signals
function parseLogForActivity(message) {
  const msg = message.toLowerCase();

  // Scanner activity
  if (msg.includes('[scanner]') && msg.includes('signal forwarded')) {
    addTradeActivity({ type: 'signal_forwarded', message });
  }

  if (msg.includes('[scanner]') && msg.includes('scanned:')) {
    addTradeActivity({ type: 'token_scanned', message });
  }

  if (msg.includes('[alpha-scout]') && msg.includes('new token from pumpportal')) {
    addTradeActivity({ type: 'new_token_detected', message });
  }

  if (msg.includes('[scanner]') && msg.includes('dexscreener')) {
    addTradeActivity({ type: 'dexscreener_update', message });
  }

  // Smart money
  if (msg.includes('cluster detected') || msg.includes('smart_money_cluster') || msg.includes('[smart-money] cluster')) {
    addTradeActivity({ type: 'smart_money_alert', message });
  }

  if (msg.includes('[smart-money]') && msg.includes('tracking')) {
    addTradeActivity({ type: 'smart_money_update', message });
  }

  // Trading activity
  if (msg.includes('dca') && (msg.includes('executed') || msg.includes('entry'))) {
    addTradeActivity({ type: 'dca_entry', message });
  }

  if (msg.includes('exit') && (msg.includes('triggered') || msg.includes('sold'))) {
    addTradeActivity({ type: 'exit', message });
  }

  if (msg.includes('position') && (msg.includes('opened') || msg.includes('created'))) {
    addTradeActivity({ type: 'position_opened', message });
  }

  if (msg.includes('position') && (msg.includes('closed') || msg.includes('cancelled'))) {
    addTradeActivity({ type: 'position_closed', message });
  }

  // Safety
  if (msg.includes('honeypot') || msg.includes('rugcheck failed') || msg.includes('denylist')) {
    addTradeActivity({ type: 'safety_alert', message });
  }

  if (msg.includes('rugcheck') && msg.includes('passed')) {
    addTradeActivity({ type: 'rugcheck_passed', message });
  }
}

ipcMain.handle('chat:send', async (_, message) => {
  const config = loadConfig();
  const apiKey = config.OPENROUTER_API_KEY;
  if (!apiKey) {
    return { error: 'No OpenRouter API key set. Go to Settings and add one.' };
  }

  const botStatus = botProcess ? 'running' : 'stopped';
  const recentLogs = botLogs.slice(-20).map(l => `[${l.level}] ${l.message}`).join('\n');
  const recentTrades = tradeActivity.slice(-10).map(t => {
    const ago = Math.round((Date.now() - t.timestamp) / 60000);
    return `[${ago}m ago] ${t.type}: ${t.message}`;
  }).join('\n');

  const systemPrompt = `You are Wildtrade — an elite Solana alpha hunter and the user's personal trading partner. You're not a generic chatbot — you are an experienced degen trader who's managing their portfolio and making moves to turn ${config.TOTAL_BUDGET_SOL || '1.0'} SOL into 10 SOL.

PERSONALITY & TONE:
- You're their sharp, experienced trading buddy — confident, street-smart, and direct
- Use trading slang naturally: "aping in", "bags", "moonshot", "rugged", "based", "degen", "LFG", "diamond hands", "paper hands"
- Be genuinely excited about good signals: "yo this one looks JUICY"
- Be cautious about risks: "nah that's looking sketchy, top 10 holders own 80%"
- Be honest about losses: "our bag on that took a hit, down 40% — watching the 1h chart"
- Keep it SHORT and punchy. 2-4 sentences max unless they ask for detail
- Give play-by-play updates like you're texting from a trading desk
- Think out loud about what you're seeing in the market

WHAT YOU'RE ACTIVELY DOING RIGHT NOW:
- Running 3 AI agents: Scout (scans PumpFun + DexScreener for new tokens), Executioner (trades them), Fixer (handles errors/safety)
- Scout is connected to PumpPortal WebSocket catching new token launches in REAL-TIME
- Every 2 minutes, Scout polls DexScreener for trending/boosted Solana tokens
- Every 3 minutes, monitoring ${config.SMART_MONEY_WALLETS ? 'custom + curated' : '20 curated'} smart money wallets for cluster buys
- Every discovered token goes through: RugCheck → DexScreener data → scoring → if score >= 65, forward to Trader
- Trader uses DCA strategy: 20% first leg, 30% second, 50% third (if conviction stays high)
- Exit tiers: sell 50% at 2x, sell 25% at 5x, let 25% ride to 10x

CURRENT STATE:
- Bot: ${botStatus}
- Mode: ${config.PAPER_TRADING !== false ? 'PAPER TRADING (sim mode, no real money on the line)' : 'LIVE TRADING (real SOL at risk!)'}
- Budget: ${config.TOTAL_BUDGET_SOL || '1.0'} SOL
- Auto mode: ${config.AUTONOMOUS_MODE === true ? 'Full auto — I make the calls' : 'Semi-auto — I flag opportunities for you'}
- Models: Scout=${config.FINDER_MODEL || 'claude-sonnet-4-5'}, Trader=${config.TRADER_MODEL || 'gpt-4o-mini'}

SETUP STATUS:
- OpenRouter API: ${apiKey ? 'Connected' : 'MISSING — need this to think'}
- Helius RPC: ${config.HELIUS_API_KEY ? 'Active — fast data' : 'Not set — using public RPC (slower, may rate limit)'}
- Twitter KOL: ${config.TWITTER_BEARER_TOKEN ? 'Active — watching influencers' : 'Not set — missing social alpha'}
- Wallet: ${config.WALLET_PUBLIC_KEY && config.WALLET_PUBLIC_KEY !== '11111111111111111111111111111111' ? 'Live wallet configured' : 'Paper wallet (default)'}
- Smart Wallets: ${config.SMART_MONEY_WALLETS ? 'Custom + curated wallets' : 'Using 20 curated smart money wallets (GMGN fallback)'}

RECENT ACTIVITY (last few minutes):
${recentTrades || '(quiet right now — no signals or trades yet)'}

RECENT LOGS:
${recentLogs || '(no logs — bot might be stopped)'}

HOW TO RESPOND:
- If user says hi/hello: Give a quick status briefing — what you're watching, any recent signals, market vibes
- If user asks about a specific token: Check if you've scanned it, what the score was, smart money activity
- If user asks "what are you doing": Describe your active scanning — PumpFun tokens coming in, DexScreener trending, smart money movements
- If user asks to start: Tell them you're firing up all systems and what happens next
- If user asks about trades: Report on any signals forwarded, DCA entries, exits
- If user asks about status: Quick tactical brief on all systems
- If there are errors: Diagnose them plainly — "looks like the RPC is rate limiting us" not "an error occurred"
- Be proactive: "btw I noticed X" or "heads up, smart money is rotating into Y"
- If asked about the 10 SOL challenge: Explain the strategy and how the scoring works in plain English
- ALWAYS reference real data from the logs and trade activity above. Don't make things up — if you don't see data, say "haven't caught any signals yet, still scanning"`;

  chatHistory.push({ role: 'user', content: message });

  if (chatHistory.length > 30) {
    chatHistory = chatHistory.slice(-24);
  }

  try {
    const https = require('https');
    const response = await new Promise((resolve, reject) => {
      const body = JSON.stringify({
        model: config.AUDITOR_MODEL || 'openai/gpt-4o-mini',
        messages: [
          { role: 'system', content: systemPrompt },
          ...chatHistory,
        ],
        max_tokens: 800,
        temperature: 0.8,
      });

      const req = https.request({
        hostname: 'openrouter.ai',
        path: '/api/v1/chat/completions',
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${apiKey}`,
          'HTTP-Referer': 'https://github.com/savilionmusic/Wildtrade',
          'X-Title': 'Wildtrade Desktop',
        },
      }, (res) => {
        let data = '';
        res.on('data', chunk => data += chunk);
        res.on('end', () => {
          try {
            resolve(JSON.parse(data));
          } catch (e) {
            reject(new Error('Invalid response from OpenRouter'));
          }
        });
      });

      req.on('error', reject);
      req.write(body);
      req.end();
    });

    if (response.error) {
      return { error: response.error.message || 'OpenRouter API error' };
    }

    const reply = response.choices?.[0]?.message?.content || 'No response from model.';
    chatHistory.push({ role: 'assistant', content: reply });
    return { reply };

  } catch (err) {
    return { error: `Chat failed: ${err.message}` };
  }
});

ipcMain.handle('chat:clear', () => {
  chatHistory = [];
  return { ok: true };
});

// ── App lifecycle ──
app.whenReady().then(createWindow);

app.on('window-all-closed', () => {
  stopBot();
  app.quit();
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) createWindow();
});

app.on('before-quit', () => {
  stopBot();
});
