const { app, BrowserWindow, ipcMain, nativeTheme, shell } = require('electron');
const path = require('path');
const fs = require('fs');
const { fork } = require('child_process');

let mainWindow = null;
let botProcess = null;
let botLogs = [];
const MAX_LOGS = 500;

// ── Config paths ──
function getConfigDir() {
  const dir = path.join(app.getPath('userData'), 'config');
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  return dir;
}

function getConfigPath() {
  return path.join(getConfigDir(), 'settings.json');
}

function loadConfig() {
  try {
    const raw = fs.readFileSync(getConfigPath(), 'utf-8');
    return JSON.parse(raw);
  } catch {
    return {};
  }
}

function saveConfig(config) {
  fs.writeFileSync(getConfigPath(), JSON.stringify(config, null, 2));
}

// ── Write .env from config ──
function writeEnvFile(config) {
  const botDir = app.isPackaged
    ? path.join(process.resourcesPath, 'bot')
    : path.join(__dirname, '..');

  const lines = [
    `# Auto-generated by Wildtrade Desktop`,
    `SOLANA_RPC_HELIUS=${config.SOLANA_RPC_HELIUS || 'https://mainnet.helius-rpc.com/?api-key=YOUR_KEY'}`,
    `SOLANA_RPC_QUICKNODE=${config.SOLANA_RPC_QUICKNODE || ''}`,
    `SOLANA_RPC_PUBLIC=https://api.mainnet-beta.solana.com`,
    `HELIUS_API_KEY=${config.HELIUS_API_KEY || ''}`,
    `HELIUS_WEBHOOK_URL=${config.HELIUS_WEBHOOK_URL || ''}`,
    `HELIUS_WEBHOOK_SECRET=${config.HELIUS_WEBHOOK_SECRET || ''}`,
    `WALLET_PRIVATE_KEY=${config.WALLET_PRIVATE_KEY || ''}`,
    `WALLET_PUBLIC_KEY=${config.WALLET_PUBLIC_KEY || '11111111111111111111111111111111'}`,
    `PAPER_TRADING=${config.PAPER_TRADING !== false ? 'true' : 'false'}`,
    `AUTONOMOUS_MODE=${config.AUTONOMOUS_MODE === true ? 'true' : 'false'}`,
    `MAX_POSITION_SIZE_SOL=${config.MAX_POSITION_SIZE_SOL || '1.0'}`,
    `TOTAL_BUDGET_SOL=${config.TOTAL_BUDGET_SOL || '1.0'}`,
    `MIN_SCORE_THRESHOLD=${config.MIN_SCORE_THRESHOLD || '65'}`,
    `DCA_DELAY_LEG1_MS=${config.DCA_DELAY_LEG1_MS || '120000'}`,
    `DCA_DELAY_LEG2_MS=${config.DCA_DELAY_LEG2_MS || '300000'}`,
    `JUPITER_API_BASE=https://quote-api.jup.ag/v6`,
    `JUPITER_SLIPPAGE_BPS=${config.JUPITER_SLIPPAGE_BPS || '300'}`,
    `RUGCHECK_API_BASE=https://api.rugcheck.xyz/v1`,
    `RUGCHECK_MIN_SCORE=${config.RUGCHECK_MIN_SCORE || '70'}`,
    `PUMPPORTAL_WS_URL=wss://pumpportal.fun/api/data`,
    `TWITTER_USERNAME=${config.TWITTER_USERNAME || ''}`,
    `TWITTER_PASSWORD=${config.TWITTER_PASSWORD || ''}`,
    `TWITTER_EMAIL=${config.TWITTER_EMAIL || ''}`,
    `TWITTER_TOKEN=${config.TWITTER_TOKEN || ''}`,
    `TWITTER_API_BASE=${config.TWITTER_API_BASE || 'https://ai.6551.io'}`,
    `TWITTER_BEARER_TOKEN=${config.TWITTER_BEARER_TOKEN || ''}`,
    `TWITTER_KOL_USER_IDS=${config.TWITTER_KOL_USER_IDS || ''}`,
    `TWITTER_POLL_INTERVAL_MS=${config.TWITTER_POLL_INTERVAL_MS || '60000'}`,
    `REDDIT_SUBREDDITS=${config.REDDIT_SUBREDDITS || 'SolanaCoins,memecoins,CryptoMoonShots'}`,
    `REDDIT_POLL_INTERVAL_MS=${config.REDDIT_POLL_INTERVAL_MS || '180000'}`,
    `SMART_MONEY_WALLETS=${config.SMART_MONEY_WALLETS || ''}`,
    `OPENROUTER_API_KEY=${config.OPENROUTER_API_KEY || ''}`,
    `OPENROUTER_BASE_URL=https://openrouter.ai/api/v1`,
    `FINDER_MODEL=${config.FINDER_MODEL || 'anthropic/claude-sonnet-4-5'}`,
    `TRADER_MODEL=${config.TRADER_MODEL || 'openai/gpt-4o-mini'}`,
    `AUDITOR_MODEL=${config.AUDITOR_MODEL || 'openai/gpt-4o-mini'}`,
    `SOCKET_IO_PORT=3001`,
    `SOCKET_IO_CORS_ORIGIN=http://localhost:3000`,
    `PGLITE_DATA_DIR=${path.join(getConfigDir(), 'db')}`,
    `LOG_LEVEL=info`,
  ];

  const envPath = path.join(botDir, '.env');
  fs.writeFileSync(envPath, lines.join('\n'));
  return envPath;
}

// ── Bot lifecycle ──
function startBot() {
  if (botProcess) return;

  const config = loadConfig();
  writeEnvFile(config);

  const botScript = app.isPackaged
    ? path.join(process.resourcesPath, 'bot', 'dist', 'bot.cjs')
    : path.join(__dirname, '..', 'dist', 'bot.cjs');

  if (!fs.existsSync(botScript)) {
    sendToRenderer('bot:error', 'Bot not built. Run "npm run build:bot" first.');
    return;
  }

  botLogs = [];
  sendToRenderer('bot:status', 'starting');

  botProcess = fork(botScript, [], {
    cwd: app.isPackaged ? path.join(process.resourcesPath, 'bot') : path.join(__dirname, '..'),
    env: { ...process.env, ...buildBotEnv(config) },
    stdio: ['pipe', 'pipe', 'pipe', 'ipc'],
  });

  botProcess.stdout.on('data', (data) => {
    // Split on newlines to avoid garbled multi-line log entries
    data.toString().split('\n').map(l => l.trim()).filter(Boolean).forEach(line => addLog('info', line));
  });

  botProcess.stderr.on('data', (data) => {
    data.toString().split('\n').map(l => l.trim()).filter(Boolean).forEach(line => addLog('error', line));
  });

  botProcess.on('message', (msg) => {
    handleBotMessage(msg);
    sendToRenderer('bot:message', msg);
  });

  botProcess.on('exit', (code) => {
    addLog('info', `Bot process exited with code ${code}`);
    botProcess = null;
    sendToRenderer('bot:status', 'stopped');
  });

  botProcess.on('error', (err) => {
    addLog('error', `Bot error: ${err.message}`);
    botProcess = null;
    sendToRenderer('bot:status', 'error');
  });

  sendToRenderer('bot:status', 'running');
}

function stopBot() {
  if (!botProcess) return;
  botProcess.kill('SIGTERM');
  setTimeout(() => {
    if (botProcess) {
      botProcess.kill('SIGKILL');
      botProcess = null;
    }
  }, 5000);
  sendToRenderer('bot:status', 'stopping');
}

function dotenvParse(config) {
  const env = {};
  for (const [key, value] of Object.entries(config)) {
    if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') {
      env[key] = String(value);
    }
  }
  return env;
}

// Build complete env for the bot process with all defaults
function buildBotEnv(config) {
  const parsed = dotenvParse(config);
  return {
    OPENROUTER_API_KEY: parsed.OPENROUTER_API_KEY || '',
    OPENROUTER_BASE_URL: 'https://openrouter.ai/api/v1',
    WALLET_PUBLIC_KEY: parsed.WALLET_PUBLIC_KEY || '11111111111111111111111111111111',
    WALLET_PRIVATE_KEY: parsed.WALLET_PRIVATE_KEY || '',
    SOLANA_RPC_HELIUS: parsed.SOLANA_RPC_HELIUS || 'https://api.mainnet-beta.solana.com',
    SOLANA_RPC_PUBLIC: 'https://api.mainnet-beta.solana.com',
    HELIUS_API_KEY: parsed.HELIUS_API_KEY || '',
    PAPER_TRADING: parsed.PAPER_TRADING === 'false' ? 'false' : 'true',
    AUTONOMOUS_MODE: parsed.AUTONOMOUS_MODE === 'true' ? 'true' : 'false',
    MAX_POSITION_SIZE_SOL: parsed.MAX_POSITION_SIZE_SOL || '1.0',
    TOTAL_BUDGET_SOL: parsed.TOTAL_BUDGET_SOL || '1.0',
    MIN_SCORE_THRESHOLD: parsed.MIN_SCORE_THRESHOLD || '65',
    JUPITER_API_BASE: 'https://quote-api.jup.ag/v6',
    JUPITER_SLIPPAGE_BPS: parsed.JUPITER_SLIPPAGE_BPS || '300',
    RUGCHECK_API_BASE: 'https://api.rugcheck.xyz/v1',
    RUGCHECK_MIN_SCORE: parsed.RUGCHECK_MIN_SCORE || '70',
    PUMPPORTAL_WS_URL: 'wss://pumpportal.fun/api/data',
    TWITTER_USERNAME: parsed.TWITTER_USERNAME || '',
    TWITTER_PASSWORD: parsed.TWITTER_PASSWORD || '',
    TWITTER_EMAIL: parsed.TWITTER_EMAIL || '',
    TWITTER_TOKEN: parsed.TWITTER_TOKEN || '',
    TWITTER_API_BASE: parsed.TWITTER_API_BASE || 'https://ai.6551.io',
    TWITTER_BEARER_TOKEN: parsed.TWITTER_BEARER_TOKEN || '',
    TWITTER_KOL_USER_IDS: parsed.TWITTER_KOL_USER_IDS || '',
    TWITTER_POLL_INTERVAL_MS: parsed.TWITTER_POLL_INTERVAL_MS || '120000',
    REDDIT_SUBREDDITS: parsed.REDDIT_SUBREDDITS || 'SolanaCoins,memecoins,CryptoMoonShots',
    REDDIT_POLL_INTERVAL_MS: parsed.REDDIT_POLL_INTERVAL_MS || '180000',
    SMART_MONEY_WALLETS: parsed.SMART_MONEY_WALLETS || '',
    TELEGRAM_BOT_TOKEN: parsed.TELEGRAM_BOT_TOKEN || '',
    TELEGRAM_CHAT_ID: parsed.TELEGRAM_CHAT_ID || '',
    FINDER_MODEL: parsed.FINDER_MODEL || 'anthropic/claude-sonnet-4-5',
    TRADER_MODEL: parsed.TRADER_MODEL || 'openai/gpt-4o-mini',
    AUDITOR_MODEL: parsed.AUDITOR_MODEL || 'openai/gpt-4o-mini',
    SOCKET_IO_PORT: '3001',
    SOCKET_IO_CORS_ORIGIN: 'http://localhost:3000',
    PGLITE_DATA_DIR: path.join(getConfigDir(), 'db'),
    LOG_LEVEL: 'info',
  };
}

function addLog(level, message) {
  const entry = { time: Date.now(), level, message };
  botLogs.push(entry);
  if (botLogs.length > MAX_LOGS) botLogs.shift();
  sendToRenderer('bot:log', entry);

  // Parse for trade activity to feed into chat context
  parseLogForActivity(message);
}

function sendToRenderer(channel, data) {
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send(channel, data);
  }
}

// ── Window ──
function createWindow() {
  nativeTheme.themeSource = 'dark';

  mainWindow = new BrowserWindow({
    width: 1100,
    height: 750,
    minWidth: 800,
    minHeight: 600,
    titleBarStyle: 'hiddenInset',
    backgroundColor: '#0d1117',
    webPreferences: {
      preload: path.join(__dirname, 'preload.cjs'),
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  mainWindow.loadFile(path.join(__dirname, '..', 'ui', 'index.html'));

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
}

// ── IPC Handlers ──
ipcMain.handle('config:load', () => loadConfig());
ipcMain.handle('config:save', (_, config) => {
  saveConfig(config);
  return { ok: true };
});

ipcMain.handle('bot:start', () => {
  startBot();
  return { ok: true };
});

ipcMain.handle('bot:stop', () => {
  stopBot();
  return { ok: true };
});

ipcMain.handle('bot:status', () => {
  return botProcess ? 'running' : 'stopped';
});

ipcMain.handle('bot:logs', () => botLogs);

// Open URLs in system browser (for DexScreener links etc.)
ipcMain.handle('open-external', (_, url) => {
  if (typeof url === 'string' && (url.startsWith('https://') || url.startsWith('http://'))) {
    shell.openExternal(url);
  }
});

// ── AI Chat ──

// Trade activity log for the chat to reference
let tradeActivity = [];
const MAX_TRADE_ACTIVITY = 50;

function addTradeActivity(entry) {
  tradeActivity.push({ ...entry, timestamp: Date.now() });
  if (tradeActivity.length > MAX_TRADE_ACTIVITY) tradeActivity.shift();
  // Also push to renderer as a chat notification
  sendToRenderer('bot:trade-update', entry);
}

// Parse bot logs for trade activity and smart money signals
function parseLogForActivity(message) {
  const msg = message.toLowerCase();

  // Scanner activity
  if (msg.includes('[scanner]') && msg.includes('signal forwarded')) {
    addTradeActivity({ type: 'signal_forwarded', message });
  }

  if (msg.includes('[scanner]') && msg.includes('scanned:')) {
    addTradeActivity({ type: 'token_scanned', message });
  }

  if (msg.includes('[alpha-scout]') && msg.includes('new token from pumpportal')) {
    addTradeActivity({ type: 'new_token_detected', message });
  }

  if (msg.includes('[scanner]') && msg.includes('dexscreener')) {
    addTradeActivity({ type: 'dexscreener_update', message });
  }

  // Smart money
  if (msg.includes('cluster detected') || msg.includes('smart_money_cluster') || msg.includes('[smart-money] cluster')) {
    addTradeActivity({ type: 'smart_money_alert', message });
  }

  if (msg.includes('[smart-money]') && msg.includes('tracking')) {
    addTradeActivity({ type: 'smart_money_update', message });
  }

  // Trading activity — match actual autonomous trader log format
  if (msg.includes('[trader]') && (msg.includes('dca leg') || msg.includes('entering position'))) {
    addTradeActivity({ type: 'dca_entry', message });
  }

  if (msg.includes('[trader]') && (msg.includes('exit tier') || msg.includes('take-profit'))) {
    addTradeActivity({ type: 'exit', message });
  }

  if (msg.includes('[trader]') && msg.includes('stop loss')) {
    addTradeActivity({ type: 'exit', message });
  }

  if (msg.includes('[trader]') && msg.includes('entering position')) {
    addTradeActivity({ type: 'position_opened', message });
  }

  if (msg.includes('[trader]') && msg.includes('position closed')) {
    addTradeActivity({ type: 'position_closed', message });
  }

  // Convergence
  if (msg.includes('[convergence]') && msg.includes('convergence:')) {
    addTradeActivity({ type: 'smart_money_cluster', message });
  }

  // Safety
  if (msg.includes('honeypot') || msg.includes('rugcheck failed') || msg.includes('denylist')) {
    addTradeActivity({ type: 'safety_alert', message });
  }

  if (msg.includes('rugcheck') && msg.includes('passed')) {
    addTradeActivity({ type: 'rugcheck_passed', message });
  }
}

ipcMain.handle('chat:send', async (_, message) => {
  // Route through ElizaOS agent when bot is running
  if (botProcess) {
    return chatViaBotIPC(message);
  }
  // Fallback to direct OpenRouter when bot is stopped
  return chatViaOpenRouter(message);
});

// ── Chat via Bot IPC (ElizaOS Agent) ──
let chatIPCCounter = 0;
const pendingChatResponses = new Map();

function chatViaBotIPC(message) {
  return new Promise((resolve) => {
    const id = ++chatIPCCounter;
    const timeout = setTimeout(() => {
      pendingChatResponses.delete(id);
      // If IPC times out, fall back to direct OpenRouter
      resolve(chatViaOpenRouter(message));
    }, 30000);

    pendingChatResponses.set(id, { resolve, timeout });
    botProcess.send({ type: 'chat:message', id, text: message });
  });
}

// Handle IPC responses from bot process
function handleBotMessage(msg) {
  if (!msg || typeof msg !== 'object') return;

  if (msg.type === 'chat:response' || msg.type === 'portfolio:response' || msg.type === 'portfolio:reset-response') {
    const pending = pendingChatResponses.get(msg.id);
    if (pending) {
      clearTimeout(pending.timeout);
      pendingChatResponses.delete(msg.id);
      if (msg.type === 'portfolio:response') {
        pending.resolve(msg.data);
      } else if (msg.type === 'portfolio:reset-response') {
        pending.resolve(msg.data);
      } else if (msg.error) {
        pending.resolve({ error: msg.text });
      } else {
        pending.resolve({ reply: msg.text, action: msg.action });
      }
    }
  }

  if (msg.type === 'chat:action-result') {
    // Action was triggered by the agent — show result in chat
    sendToRenderer('bot:trade-update', {
      type: 'agent_action',
      action: msg.action,
      message: msg.result || `Action ${msg.action} executed`,
    });
  }

  if (msg.type === 'proactive-alert') {
    // Proactive alert from scanner/smart money — push to chat
    sendToRenderer('bot:trade-update', {
      type: msg.alertType || 'alert',
      message: msg.message,
    });
  }
}

// ── Fallback: Direct OpenRouter chat (when bot is stopped) ──
let chatHistory = [];

async function chatViaOpenRouter(message) {
  const config = loadConfig();
  const apiKey = config.OPENROUTER_API_KEY;
  if (!apiKey) {
    return { error: 'No OpenRouter API key set. Go to Settings and add one.' };
  }

  const botStatus = botProcess ? 'running' : 'stopped';
  const recentLogs = botLogs.slice(-15).map(l => `[${l.level}] ${l.message}`).join('\n');

  const systemPrompt = `You are Scout (Wildtrade) — an elite Solana trading partner. The bot is currently ${botStatus}. ${botStatus === 'stopped' ? 'Tell the user to start the bot so you can begin scanning and trading. Once running, you route through ElizaOS with full agent capabilities.' : ''}

Quick context: You lead 3 agents (Scout finds tokens, Executioner trades, Fixer handles safety). PumpPortal + DexScreener scanning, smart money wallet tracking, RugCheck on every token. DCA entries, tiered exits. Goal: turn ${config.TOTAL_BUDGET_SOL || '1.0'} SOL into 10 SOL.

Keep responses short and punchy (2-4 sentences). Use trading slang naturally.

Recent logs:
${recentLogs || '(no logs)'}`;

  chatHistory.push({ role: 'user', content: message });
  if (chatHistory.length > 20) chatHistory = chatHistory.slice(-16);

  try {
    const https = require('https');
    const response = await new Promise((resolve, reject) => {
      const body = JSON.stringify({
        model: config.FINDER_MODEL || 'anthropic/claude-sonnet-4-5',
        messages: [
          { role: 'system', content: systemPrompt },
          ...chatHistory,
        ],
        max_tokens: 600,
        temperature: 0.8,
      });

      const req = https.request({
        hostname: 'openrouter.ai',
        path: '/api/v1/chat/completions',
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${apiKey}`,
          'HTTP-Referer': 'https://github.com/savilionmusic/Wildtrade',
          'X-Title': 'Wildtrade Desktop',
        },
      }, (res) => {
        let data = '';
        res.on('data', chunk => data += chunk);
        res.on('end', () => {
          try { resolve(JSON.parse(data)); }
          catch (e) { reject(new Error('Invalid response from OpenRouter')); }
        });
      });
      req.on('error', reject);
      req.write(body);
      req.end();
    });

    if (response.error) {
      return { error: response.error.message || 'OpenRouter API error' };
    }

    const reply = response.choices?.[0]?.message?.content || 'No response from model.';
    chatHistory.push({ role: 'assistant', content: reply });
    return { reply };
  } catch (err) {
    return { error: `Chat failed: ${err.message}` };
  }
}

ipcMain.handle('chat:clear', () => {
  chatHistory = [];
  return { ok: true };
});

// ── Portfolio IPC ──
ipcMain.handle('portfolio:get', async () => {
  if (!botProcess) {
    return { positions: [], history: [], budget: 0, deployed: 0, available: 0, realized: 0, winRate: 0, trades: 0, paper: true };
  }
  return new Promise((resolve) => {
    const id = ++chatIPCCounter;
    const timeout = setTimeout(() => {
      pendingChatResponses.delete(id);
      resolve({ positions: [], history: [], budget: 0, deployed: 0, available: 0, realized: 0, winRate: 0, trades: 0, paper: true });
    }, 5000);
    pendingChatResponses.set(id, { resolve, timeout });
    botProcess.send({ type: 'portfolio:get', id });
  });
});

ipcMain.handle('config:set-runtime', (_, key, value) => {
  if (botProcess) {
    botProcess.send({ type: 'config:set', key, value });
  }
});

ipcMain.handle('portfolio:reset', async () => {
  if (!botProcess) return 'Bot not running';
  return new Promise((resolve) => {
    const id = ++chatIPCCounter;
    const timeout = setTimeout(() => {
      pendingChatResponses.delete(id);
      resolve('Reset timed out');
    }, 5000);
    pendingChatResponses.set(id, { resolve, timeout });
    botProcess.send({ type: 'portfolio:reset', id });
  });
});

// ── App lifecycle ──
app.whenReady().then(createWindow);

app.on('window-all-closed', () => {
  stopBot();
  app.quit();
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) createWindow();
});

app.on('before-quit', () => {
  stopBot();
});
